using Test

include("test_adapter.jl")
include("test_end_to_end.jl")
include("test_fast_path_detection.jl")
include("test_fast_path_agrees.jl")
include("test_constraints.jl")
include("test_latent_layout.jl")
include("test_named_marginals.jl")
include("test_obs_groups.jl")
include("test_latte_macro.jl")
include("test_recognition.jl")
include("test_prelude_lift.jl")
include("test_prelude_lift_codegen.jl")
include("test_prelude_lift_end_to_end.jl")
include("test_dag_assembly_plan.jl")
include("test_dag_sparse_ad_plan.jl")
include("test_turing_handoff.jl")
