<script setup lang="ts">
import scalingData from '../data/scaling_curve.json'

// One spatial Poisson–Matérn (SPDE) model fit at five mesh resolutions, on a
// shared mesh handed to both engines. Wall-clock of the full INLA fit vs latent
// dimension n, log–log. Latte: serial + threaded; R-INLA: serial + parallel
// ("10:1"). Generated by `benchmark/scaling/render_scaling.jl`.
type Lvl = {
  n: number; m: number
  latte_serial: number; latte_threaded: number
  rinla_serial: number; rinla_parallel: number
}
const levels = scalingData.levels as Lvl[]
const caveat = scalingData.caveat as string

// ── geometry (log–log) ──
const W = 640, H = 380
const ML = 56, MR = 150, MT = 24, MB = 52
const x0 = ML, x1 = W - MR, y0 = H - MB, y1 = MT
const NMIN = 450, NMAX = 32000        // x domain (latent dim)
const TMIN = 0.15, TMAX = 90          // y domain (seconds)

const lx = (n: number) => Math.log10(n)
const ly = (t: number) => Math.log10(t)
const gx = (n: number) => +(x0 + (lx(n) - lx(NMIN)) / (lx(NMAX) - lx(NMIN)) * (x1 - x0)).toFixed(1)
const gy = (t: number) => +(y0 - (ly(t) - ly(TMIN)) / (ly(TMAX) - ly(TMIN)) * (y0 - y1)).toFixed(1)

const xticks = [500, 1000, 3000, 10000, 30000]
const xtlab = (t: number) => (t >= 1000 ? `${t / 1000}k` : `${t}`)
const yticks = [0.3, 1, 3, 10, 30]

type Series = { key: keyof Lvl; label: string; cls: string; dashed: boolean }
const series: Series[] = [
  { key: 'rinla_serial',   label: 'R-INLA serial',   cls: 'rinla', dashed: false },
  { key: 'rinla_parallel', label: 'R-INLA parallel', cls: 'rinla', dashed: true },
  { key: 'latte_serial',   label: 'Latte serial',    cls: 'latte', dashed: false },
  { key: 'latte_threaded', label: 'Latte threaded',  cls: 'latte', dashed: true },
]
const path = (s: Series) => levels.map(l => `${gx(l.n)},${gy(l[s.key] as number)}`).join(' ')

// legend anchor (top-right gutter)
const lgX = x1 + 16
const lgY0 = MT + 8
</script>

<template>
  <figure class="scl">
    <div class="scl-head">
      <div class="scl-eyebrow">SCALING · SPATIAL POISSON–MATÉRN · FULL FIT</div>
      <h3>Wall-clock against <em>problem size.</em></h3>
      <p class="scl-sub">one SPDE model on a shared mesh · five resolutions · same posterior</p>
    </div>

    <svg :viewBox="`0 0 ${W} ${H}`" class="scl-svg" role="img"
         aria-label="Log-log plot of fit wall-clock versus latent dimension, Latte and R-INLA, serial and parallel.">
      <!-- axes -->
      <line class="scl-ax" :x1="x0" :y1="y0" :x2="x1" :y2="y0" />
      <line class="scl-ax" :x1="x0" :y1="y0" :x2="x0" :y2="y1" />

      <!-- x ticks -->
      <g v-for="t in xticks" :key="'x' + t">
        <line class="scl-tick" :x1="gx(t)" :y1="y0" :x2="gx(t)" :y2="y0 + 4" />
        <text class="scl-tlab" :x="gx(t)" :y="y0 + 16" text-anchor="middle">{{ xtlab(t) }}</text>
      </g>
      <text class="scl-axlab" :x="(x0 + x1) / 2" :y="H - 10" text-anchor="middle">latent dimension n  (log) →</text>

      <!-- y ticks -->
      <g v-for="t in yticks" :key="'y' + t">
        <line class="scl-tick" :x1="x0 - 4" :y1="gy(t)" :x2="x0" :y2="gy(t)" />
        <text class="scl-tlab" :x="x0 - 8" :y="gy(t) + 3" text-anchor="end">{{ t }}s</text>
      </g>
      <text class="scl-axlab" :x="15" :y="(y0 + y1) / 2" text-anchor="middle"
            :transform="`rotate(-90 15 ${(y0 + y1) / 2})`">fit wall-clock · lower = faster</text>

      <!-- series -->
      <g v-for="s in series" :key="s.key">
        <polyline class="scl-line" :class="[s.cls, { dashed: s.dashed }]" :points="path(s)" />
        <circle v-for="l in levels" :key="s.key + l.n"
                class="scl-dot" :class="s.cls" :cx="gx(l.n)" :cy="gy(l[s.key] as number)"
                :r="s.dashed ? 2.6 : 3.4" :fill-opacity="s.dashed ? 0.55 : 1" />
      </g>

      <!-- legend -->
      <g v-for="(s, i) in series" :key="'lg' + s.key">
        <line class="scl-line" :class="[s.cls, { dashed: s.dashed }]"
              :x1="lgX" :y1="lgY0 + i * 19" :x2="lgX + 22" :y2="lgY0 + i * 19" />
        <text class="scl-lglab" :x="lgX + 28" :y="lgY0 + i * 19 + 3.5">{{ s.label }}</text>
      </g>
    </svg>

    <table class="scl-table">
      <thead>
        <tr>
          <th>n</th><th>Latte<br>serial</th><th>Latte<br>threaded</th>
          <th>R-INLA<br>serial</th><th>R-INLA<br>parallel</th>
          <th>Latte thr ÷<br>R-INLA par</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="l in levels" :key="'r' + l.n">
          <td>{{ l.n.toLocaleString() }}</td>
          <td>{{ l.latte_serial.toFixed(2) }}s</td>
          <td>{{ l.latte_threaded.toFixed(2) }}s</td>
          <td>{{ l.rinla_serial.toFixed(2) }}s</td>
          <td>{{ l.rinla_parallel.toFixed(2) }}s</td>
          <td class="gain">{{ (l.rinla_parallel / l.latte_threaded).toFixed(1) }}×</td>
        </tr>
      </tbody>
    </table>

    <p class="scl-foot">
      Latte's <em>serial</em> fit tracks R-INLA's <em>parallel</em> fit at the top end and beats it below it;
      threaded, it leads at every size. R-INLA gains more from threads (steeper self-speedup) off a slower
      serial baseline, so absolute wall-clock still favors Latte here. {{ caveat }}
    </p>
  </figure>
</template>

<style scoped>
.scl {
  --tan: #E8D5B7; --caramel: #C9986A; --mocha: #8B6F47; --bean: #3D2817;
  --berry: #C04A2A; --foam: #FFFCF7;
  max-width: 820px; margin: 0 auto 8px; padding: 30px 34px;
  background: var(--foam); border: 1px solid var(--tan); border-radius: 14px;
  font-family: 'Inter', system-ui, sans-serif;
}
.scl-head { text-align: center; margin-bottom: 14px; }
.scl-eyebrow { font-family: 'JetBrains Mono', monospace; font-size: 11px; letter-spacing: 1.4px; color: var(--caramel); margin-bottom: 10px; }
.scl-head h3 { font-family: 'Fraunces', Georgia, serif; font-style: italic; font-weight: 400; font-size: 27px; letter-spacing: -0.4px; margin: 0; color: var(--bean); line-height: 1.12; }
.scl-head h3 em { font-style: italic; color: var(--berry); }
.scl-sub { font-size: 12.5px; color: var(--mocha); margin: 8px 0 0; font-family: 'JetBrains Mono', monospace; }

.scl-svg { width: 100%; height: auto; display: block; }
.scl-ax { stroke: rgba(139, 111, 71, 0.55); stroke-width: 1; }
.scl-tick { stroke: rgba(139, 111, 71, 0.55); stroke-width: 1; }
.scl-tlab { fill: var(--mocha); font-size: 11px; font-family: 'JetBrains Mono', monospace; }
.scl-axlab { fill: var(--mocha); font-size: 11px; font-family: 'JetBrains Mono', monospace; letter-spacing: 0.3px; }

.scl-line { fill: none; stroke-width: 1.8; }
.scl-line.latte { stroke: var(--berry); }
.scl-line.rinla { stroke: var(--bean); }
.scl-line.dashed { stroke-dasharray: 5 4; stroke-width: 1.5; }
.scl-dot.latte { fill: var(--berry); }
.scl-dot.rinla { fill: var(--bean); }
.scl-lglab { fill: var(--bean); font-size: 11.5px; font-family: 'JetBrains Mono', monospace; }

.scl-table {
  width: 100%; border-collapse: collapse; margin: 18px 0 4px;
  font-family: 'JetBrains Mono', monospace; font-size: 12px; color: var(--bean);
}
.scl-table th {
  font-weight: 500; color: var(--mocha); text-align: right;
  padding: 4px 10px; border-bottom: 1px solid var(--tan); font-size: 10.5px; line-height: 1.25;
}
.scl-table th:first-child, .scl-table td:first-child { text-align: left; }
.scl-table td { text-align: right; padding: 5px 10px; border-bottom: 1px solid rgba(232, 213, 183, 0.5); }
.scl-table td.gain { color: var(--berry); font-weight: 600; }

.scl-foot { font-size: 11.5px; color: var(--mocha); margin: 12px 2px 0; line-height: 1.5; }
.scl-foot em { font-style: italic; color: var(--bean); }

@media (max-width: 640px) {
  .scl-table { font-size: 10.5px; }
  .scl-table th, .scl-table td { padding: 4px 5px; }
}
</style>
